#!/bin/sh
cd ~/otr/newer/Kamek
python tools/mapfile_tool.py
python tools/kamek.py NewerProjectKP.yaml --no-rels --use-clang --gcc-type=/opt/wiidev/bin/powerpc-elf --llvm-path=/home/me/Dev/llvm-build/bin
if [ "$?" = "0" ]; then
	echo "compile successful"
else
	exit 1
fi

copy_files() {
	cp NewerASM/n_$1_loader.bin ~/otr/dolphin/Dolphin/files/NewerRes/System$2.bin
	cp NewerASM/n_$1_dlcode.bin ~/otr/dolphin/Dolphin/files/NewerRes/DLCode$2.bin
	cp NewerASM/n_$1_dlrelocs.bin ~/otr/dolphin/Dolphin/files/NewerRes/DLRelocs$2.bin
}

copy_files pal EU_1
copy_files pal2 EU_2
copy_files ntsc US_1
copy_files ntsc2 US_2
copy_files jpn JP_1
copy_files jpn2 JP_2

echo Built all!

